version: '3.2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/../static
    depends_on:
      - web

  web:
    build: .
    container_name: django
    restart: always
    env_file:
      - .env
    command: bash -c "
      python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn django_app.wsgi -c config/gunicorn/settings.conf.py"
    depends_on:
      - db
    links:
      - db
      - redis
    volumes:
      - .:/src
      - /static:/../static
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/run/postgresql/
    expose:
      - "5432"

  redis:
    image: redis:latest
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      celery worker
      -A django_app.celery:app
      -Q default --loglevel=debug
      -f logs/celery.log"
    volumes:
      - .:/src
    links:
      - db
      - redis
    env_file:
      - .env
    depends_on:
      - redis

  nodejs:
    build:
      context: .
      dockerfile: ./config/node/Dockerfile
    volumes:
      - .:/src
      - ./logs/nodejs/:/root/.npm/_logs/
      - ./static/js/dist:/src/static/js/dist
      - ./static/js/dist/css:/src/static/js/dist/css
    command: npm start
    links:
      - web:web
