version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django
    environment:
      SECRET_KEY: 'very_secret_key'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn main.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/src
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: db
    environment:
        POSTGRES_DB: blog
        POSTGRES_USER: django
        POSTGRES_PASSWORD: ololo
    expose:
      - "5432"