web:
  restart: always
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: main.settings
    SECRET_KEY: verysecretkey
  expose:
    - "8000"
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
  volumes:
    - .:/app
  command: python manage.py runserver

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  ports:
    - "5432:5432"
