# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_hash',
            field=models.CharField(max_length=400),
        ),
    ]
