# Generated by Django 2.0a1 on 2017-10-30 22:02

from django.db import migrations, models


# def create_user_names():
#     pass


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20171028_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        # migrations.RunPython(create_user_names),
    ]
